source ~/.zsh/environment.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
#source ~/.zsh/prompt_256.zsh
source ~/.zsh/ohmy.zsh

# vim-promptline! (generated by :PromptlineSnapshot ~/.zsh/promtpline.sh
# airline)
#source ~/.zsh/promptline.sh
