source ~/.zsh/environment.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
#source ~/.zsh/prompt_256.zsh
source ~/.zsh/ohmy.zsh

# For some reason, oh-my-zsh overwrites some environment variables.
# I don't know why it does this, and I'm not sure I'm safe sourcing
# environment.zsh after sourcing ohmy.zsh. For now, fixing some
# environment here:

export LESS="-FXRS"

# vim-promptline! (generated by :PromptlineSnapshot ~/.zsh/promtpline.sh
# airline)
#source ~/.zsh/promptline.sh
