#! /bin/sh

xrdb ~/.Xresources

sxhkd &

if test "$(hostname)" = "pp-lap-dbe"; then
    bspc monitor eDP-1 -d iota gamma mu delta lambda kappa
    bspc monitor HDMI-2 -d iota gamma mu delta lambda kappa
elif test "$(hostname)" = "pp-ws-dbe"; then
    ${HOME}/bin/setup-screens
    synergys -c ${HOME}/.synergy.conf
    #xrandr --output HDMI-0 --mode 1920x1080 --pos 0x1080 --output DVI-D-0 --pos 0x0 --output DP-1 --mode 1920x1080 --rotate left --pos 1920x240
    bspc monitor DVI-1 -d iota gamma mu delta lambda kappa
    bspc monitor DisplayPort-1 -d iota gamma mu delta lambda kappa
    bspc monitor DisplayPort-0 -d iota gamma mu delta lambda kappa
    feh --bg-center /home/dbe/Dropbox/bgs/light/173.jpg /home/dbe/Dropbox/bgs/light/94.jpg /home/dbe/Dropbox/bgs/light/Lake\ Tahoe\ Colors.jpg
    polybar work1 &
else
    bspc monitor -d iota gamma mu delta lambda kappa
fi

bspc config border_width         0
bspc config window_gap          37

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#compton -b

# set left_ptr in x root (wallpaper)
#xsetroot -cursor_name left_ptr
xsetroot -xcf /usr/share/icons/whiteglass/cursors/left_ptr 16
