#! /bin/sh

sxhkd &

if test "$(hostname)" = "pp-lap-dbe"; then
    bspc monitor eDP-1 -d iota gamma mu delta lambda kappa
    bspc monitor HDMI-2 -d iota gamma mu delta lambda kappa
else
    bspc monitor -d iota gamma mu delta lambda kappa
fi

bspc config border_width         0
bspc config window_gap          37

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b
