# Common commands and aliases.
alias ls="ls --color -F --group-directories-first"
alias lsof="lsof -Pn"
alias mmv='noglob zmv -W'
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias pgr="vimpager"
alias rm="rm -v"
alias mv="mv -v"
alias ds="dirs -v"
alias ps='ps af -o pid,user,tty,command'
alias pc="pacman-color"
alias oct="octave --silent"
alias hs="ghci"
alias vim="TERM=xterm-256color vim"
alias v="TERM=xterm-256color vim"
alias c="cd"
alias o="cd"
alias a="ls --color -F --group-directories-first"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
